# Generated by Django 3.2.14 on 2022-08-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.CharField(max_length=50),
        ),
    ]
