# Generated by Django 3.2.14 on 2022-08-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_newsletter'),
        ('users', '0003_appoinment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinment',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='appoinment',
            name='gender',
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.department'),
        ),
    ]
