# Generated by Django 3.2.14 on 2022-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_patient_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
