# Generated by Django 3.2.14 on 2022-08-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220805_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
