# Generated by Django 3.2.14 on 2022-08-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='director',
        ),
    ]
